// GENERATED by verify/make-old-runner.js from commit 73d7f69. Do not edit.
// The session-01 main-thread runner, kept only to prove the worker runner
// produces byte-identical output to the one it replaced.
(function () {
  function formatArg(a) {
    if (typeof a === "string") return a;
    if (a === undefined) return "undefined";
    if (a === null) return "null";
    var t = typeof a;
    if (t === "number" || t === "boolean" || t === "bigint" || t === "symbol" || t === "function") {
      return String(a);
    }
    try { return JSON.stringify(a); }
    catch (e) { return String(a); }
  }

  function OLD_runSource(source) {
    var lines = [];
    var original = console.log;
    var threw = null;

    console.log = function () {
      var parts = [];
      for (var i = 0; i < arguments.length; i++) parts.push(formatArg(arguments[i]));
      lines.push(parts.join(" "));
    };

    try {
      // eslint-disable-next-line no-new-func
      (new Function(source))();
    } catch (err) {
      threw = err;
    } finally {
      console.log = original;
    }

    if (threw) {
      var name = (threw && threw.name) ? threw.name : "Error";
      var message = (threw && threw.message) ? threw.message : String(threw);
      lines.push(name + ": " + message);
    }

    return { output: lines.join("\n"), threw: threw ? String(threw) : null, lineCount: lines.length };
  }

  window.OLD_runSource = OLD_runSource;
})();
